name: unievents
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  cached_network_image: ^3.4.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.1
  iconsax: ^0.0.8
  email_validator: ^3.0.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  firebase_auth: ^5.2.0
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.0
  salomon_bottom_bar: ^3.3.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  marquee: ^2.3.0
  file_picker: ^10.2.0
  geolocator: ^9.0.2
  url_launcher: ^6.1.10
  share_plus: ^11.0.0
  syncfusion_flutter_pdfviewer: ^28.2.12

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
