// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLtUb7wb9c7M8nKjjrn6VgcRk-z0QHYnU',
    appId: '1:355056649988:web:fb10f84fd371fe7ed73251',
    messagingSenderId: '355056649988',
    projectId: 'unievent-2a2fb',
    authDomain: 'unievent-2a2fb.firebaseapp.com',
    storageBucket: 'unievent-2a2fb.appspot.com',
    measurementId: 'G-ZK58237NZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldoyNM9PMfVFiIlWNadMm8thQ5p4HbVA',
    appId: '1:355056649988:android:edd53c509f3f0e1ad73251',
    messagingSenderId: '355056649988',
    projectId: 'unievent-2a2fb',
    storageBucket: 'unievent-2a2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvEybLXquY0RS8rKvtl3k3MWgYD4a6lD0',
    appId: '1:355056649988:ios:b6860d327bfd0139d73251',
    messagingSenderId: '355056649988',
    projectId: 'unievent-2a2fb',
    storageBucket: 'unievent-2a2fb.appspot.com',
    iosBundleId: 'com.example.unievents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvEybLXquY0RS8rKvtl3k3MWgYD4a6lD0',
    appId: '1:355056649988:ios:b6860d327bfd0139d73251',
    messagingSenderId: '355056649988',
    projectId: 'unievent-2a2fb',
    storageBucket: 'unievent-2a2fb.appspot.com',
    iosBundleId: 'com.example.unievents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLtUb7wb9c7M8nKjjrn6VgcRk-z0QHYnU',
    appId: '1:355056649988:web:0ec16bb0bc01cb19d73251',
    messagingSenderId: '355056649988',
    projectId: 'unievent-2a2fb',
    authDomain: 'unievent-2a2fb.firebaseapp.com',
    storageBucket: 'unievent-2a2fb.appspot.com',
    measurementId: 'G-Z4W510X41K',
  );
}
